name: Deploy Guestbook
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Inject Secrets
        run: |
          sed -i "s/__GIST_ID__/${{ secrets.GIST_ID }}/g" js/config.js
          sed -i "s/__GH_TOKEN__/${{ secrets.GH_TOKEN }}/g" js/config.js
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
