name: Deploy to Neocities
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 👉 No build step needed for plain HTML/CSS/JS

      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v3
        with:
          api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
          dist_dir: '.'            # deploy everything in your repo root
          cleanup: false
          preview_before_deploy: true
